import './stuff.js';
import './Locations.js';
import './Buildings.js';
import './Categories.js';
import './Events.js';
import './Forms.js';
import './Studies.js';
import './TrashBags.js';
import './Admin.js';
